apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - image-policy.yaml
patches:
  - path: migration-patch.yaml
    target:
      kind: Job
      name: __SERVICE_NAME__-dbmigration
